//! This is for development // signinForm: 34
export const defaultValues = {
  email: "habib@gmail.com",
  password: "password123",
};

//! This is for testing
export const frameworks = [
  { value: "next.js", label: "Next.js" },
  { value: "sveltekit", label: "SvelteKit" },
  { value: "nuxt.js", label: "Nuxt.js" },
  { value: "remix", label: "Remix" },
  { value: "astro", label: "Astro" },
  { value: "vue.js", label: "Vue.js" },
  { value: "react", label: "React" },
  { value: "angular", label: "Angular" },
  { value: "ember.js", label: "Ember.js" },
  { value: "backbone.js", label: "Backbone.js" },
  { value: "jquery", label: "jQuery" },
  { value: "express.js", label: "Express.js" },
  { value: "koa.js", label: "Koa.js" },
  { value: "meteor.js", label: "Meteor.js" },
  { value: "d3.js", label: "D3.js" },
  { value: "tailwindcss", label: "Tailwind CSS" },
  { value: "bootstrap", label: "Bootstrap" },
  { value: "foundation", label: "Foundation" },
  { value: "bulma", label: "Bulma" },
  { value: "material-ui", label: "Material-UI" },
  { value: "chakra-ui", label: "Chakra UI" },
  { value: "ant-design", label: "Ant Design" },
  { value: "semantic-ui", label: "Semantic UI" },
  { value: "vuex", label: "Vuex" },
  { value: "redux", label: "Redux" },
  { value: "mobx", label: "MobX" },
  { value: "graphql", label: "GraphQL" },
  { value: "apollo", label: "Apollo" },
  { value: "firebase", label: "Firebase" },
  { value: "next-auth", label: "Next Auth" },
  { value: "rxjs", label: "RxJS" },
  { value: "lodash", label: "Lodash" },
  { value: "moment.js", label: "Moment.js" },
  { value: "date-fns", label: "Date-fns" },
  { value: "axios", label: "Axios" },
  { value: "fetch", label: "Fetch API" },
  { value: "superagent", label: "Superagent" },
  { value: "vue-router", label: "Vue Router" },
  { value: "react-router", label: "React Router" },
  { value: "redux-saga", label: "Redux-Saga" },
  { value: "redux-thunk", label: "Redux Thunk" },
  { value: "eslint", label: "ESLint" },
  { value: "prettier", label: "Prettier" },
  { value: "webpack", label: "Webpack" },
  { value: "parcel", label: "Parcel" },
  { value: "rollup", label: "Rollup" },
  { value: "vite", label: "Vite" },
  { value: "babel", label: "Babel" },
  { value: "typescript", label: "TypeScript" },
  { value: "python", label: "Python" },
  { value: "ruby", label: "Ruby" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "java", label: "Java" },
];
